import {sql} from 'slonik'


export const some_dates = sql<queries.DimDate>`
  SELECT
  date_dim_id,
  date_actual,
  day_suffix
  FROM dim_date
  LIMIT 10
`








export declare namespace queries {
    // Generated by @slonik/typegen

    /** - query: `SELECT date_dim_id, date_actual, day_suffix FROM dim_date LIMIT 10` */
    export interface DimDate {

        /** column: `public.dim_date.date_dim_id`, not null: `true`, regtype: `integer` */
        date_dim_id: number;

        /** column: `public.dim_date.date_actual`, not null: `true`, regtype: `date` */
        date_actual: Date;

        /** column: `public.dim_date.day_suffix`, not null: `true`, regtype: `character varying(4)` */
        day_suffix: string;
    }
}
